-- =====================================================================
-- SafeSphere EHS — demo tenant seed
--
-- Purpose: the sales demo and the local development fixture. This file
-- creates one organization with a complete, realistic safety loop:
--   INC-2026-0001  fall from height
--     → investigation → 5 Whys → 2 root causes → 4 CAPA actions
--     → evidence → verification → closed
-- plus 12 months of background events so every dashboard tile has data.
--
-- Run as the migration/owner role (RLS is bypassed by the owner during
-- seeding; the application role never gets that privilege).
--
--   psql "$DATABASE_URL" -f db/schema.sql -f db/seed.sql
--
-- Demo credentials (password for every seeded user): Demo!2345
-- The password_hash values below are argon2id hashes of that string,
-- regenerated by prisma/seed.ts — do not reuse them outside local/demo.
-- =====================================================================

BEGIN;

-- Fixed ids so the demo is reproducible and deep links are stable.
\set org_id       '''11111111-1111-4111-8111-111111111111'''
\set site_a       '''22222222-2222-4222-8222-222222222201'''
\set site_b       '''22222222-2222-4222-8222-222222222202'''
\set dept_civil   '''22222222-2222-4222-8222-222222222301'''
\set dept_mech    '''22222222-2222-4222-8222-222222222302'''
\set u_admin      '''33333333-3333-4333-8333-333333333301'''
\set u_hse        '''33333333-3333-4333-8333-333333333302'''
\set u_inv        '''33333333-3333-4333-8333-333333333303'''
\set u_site       '''33333333-3333-4333-8333-333333333304'''
\set u_owner      '''33333333-3333-4333-8333-333333333305'''
\set u_worker     '''33333333-3333-4333-8333-333333333306'''
\set u_exec       '''33333333-3333-4333-8333-333333333307'''
\set inc_main     '''44444444-4444-4444-8444-444444444401'''
\set investigation '''55555555-5555-4555-8555-555555555501'''
\set rc_1         '''66666666-6666-4666-8666-666666666601'''
\set rc_2         '''66666666-6666-4666-8666-666666666602'''

-- ---------------------------------------------------------------------
-- Organization + subscription
-- ---------------------------------------------------------------------
INSERT INTO organizations (id, name, slug, industry, country_code, default_timezone,
                           reference_prefix, ai_enabled, ai_monthly_budget_usd, mfa_required)
VALUES (:org_id, 'Kilimanjaro Construction Ltd', 'kilimanjaro-construction',
        'Construction & Engineering', 'TZ', 'Africa/Dar_es_Salaam', 'INC', true, 25.00, false);

INSERT INTO subscriptions (organization_id, tier, status, seat_limit, site_limit,
                           storage_limit_gb, trial_ends_at, current_period_end)
VALUES (:org_id, 'PROFESSIONAL', 'ACTIVE', 100, 10, 100, NULL, now() + interval '1 year');

-- ---------------------------------------------------------------------
-- Sites and departments
-- ---------------------------------------------------------------------
INSERT INTO sites (id, organization_id, name, code, timezone, country_code, address,
                   latitude, longitude, anonymous_reporting_enabled, anonymous_token)
VALUES
 (:site_a, :org_id, 'Dar es Salaam — Port Expansion', 'DSM-PORT', 'Africa/Dar_es_Salaam', 'TZ',
  'Kurasini, Dar es Salaam', -6.836000, 39.283000, true, 'dsm-port-8f3a21'),
 (:site_b, :org_id, 'Arusha — Ring Road Package 2',  'ARK-RR2',  'Africa/Dar_es_Salaam', 'TZ',
  'Njiro, Arusha',            -3.386900, 36.683000, true, 'ark-rr2-2c94de');

INSERT INTO departments (id, organization_id, site_id, name, code) VALUES
 (:dept_civil, :org_id, :site_a, 'Civil Works',       'CIV'),
 (:dept_mech,  :org_id, :site_a, 'Plant & Machinery', 'MECH');
INSERT INTO departments (organization_id, site_id, name, code) VALUES
 (:org_id, :site_b, 'Earthworks', 'EARTH'),
 (:org_id, NULL,    'HSE',        'HSE');

-- ---------------------------------------------------------------------
-- Users and memberships
-- password_hash below is a placeholder; prisma/seed.ts writes real argon2id hashes
-- ---------------------------------------------------------------------
INSERT INTO users (id, email, email_verified_at, password_hash, full_name, phone_e164, job_title) VALUES
 (:u_admin,  'admin@demo.safesphere.app',  now(), '$argon2id$SEED_PLACEHOLDER', 'Neema Mollel',      '+255700000001', 'IT Administrator'),
 (:u_hse,    'hse@demo.safesphere.app',    now(), '$argon2id$SEED_PLACEHOLDER', 'Grace Kimaro',      '+255700000002', 'HSE Manager'),
 (:u_inv,    'inv@demo.safesphere.app',    now(), '$argon2id$SEED_PLACEHOLDER', 'Peter Massawe',     '+255700000003', 'Safety Officer'),
 (:u_site,   'site@demo.safesphere.app',   now(), '$argon2id$SEED_PLACEHOLDER', 'Joseph Mwakalinga', '+255700000004', 'Site Manager'),
 (:u_owner,  'owner@demo.safesphere.app',  now(), '$argon2id$SEED_PLACEHOLDER', 'Fatma Juma',        '+255700000005', 'Plant Supervisor'),
 (:u_worker, 'worker@demo.safesphere.app', now(), '$argon2id$SEED_PLACEHOLDER', 'Amina Hassan',      '+255700000006', 'Steel Fixer'),
 (:u_exec,   'exec@demo.safesphere.app',   now(), '$argon2id$SEED_PLACEHOLDER', 'Salum Rashid',      '+255700000007', 'Operations Director');

INSERT INTO memberships (organization_id, user_id, role, all_sites) VALUES
 (:org_id, :u_admin,  'ORG_ADMIN',    true),
 (:org_id, :u_hse,    'HSE_MANAGER',  true),
 (:org_id, :u_inv,    'INVESTIGATOR', true),
 (:org_id, :u_site,   'SITE_MANAGER', false),
 (:org_id, :u_owner,  'ACTION_OWNER', false),
 (:org_id, :u_worker, 'EMPLOYEE',     false),
 (:org_id, :u_exec,   'EXECUTIVE',    true);

-- Site scoping for the non-all_sites members
INSERT INTO membership_sites (membership_id, site_id, organization_id)
SELECT m.id, :site_a, :org_id FROM memberships m
WHERE m.organization_id = :org_id AND m.user_id IN (:u_site, :u_owner, :u_worker);

-- ---------------------------------------------------------------------
-- Taxonomy (system defaults every new org receives)
-- ---------------------------------------------------------------------
INSERT INTO taxonomy_terms (organization_id, kind, key, label, sort_order, is_system)
SELECT :org_id, 'INCIDENT_CATEGORY', key, label, ord, true FROM (VALUES
  ('SLIP_TRIP_FALL',      'Slip, trip or fall',            10),
  ('FALL_FROM_HEIGHT',    'Fall from height',              20),
  ('STRUCK_BY',           'Struck by object',              30),
  ('CAUGHT_IN',           'Caught in or between',          40),
  ('ELECTRICAL',          'Electrical',                    50),
  ('FIRE_EXPLOSION',      'Fire or explosion',             60),
  ('CHEMICAL_EXPOSURE',   'Chemical exposure',             70),
  ('VEHICLE_PLANT',       'Vehicle or mobile plant',       80),
  ('MANUAL_HANDLING',     'Manual handling',               90),
  ('ENVIRONMENTAL',       'Environmental release',        100),
  ('PROPERTY_DAMAGE',     'Property damage',              110),
  ('SECURITY',            'Security or violence',         120)
) AS t(key,label,ord);

INSERT INTO taxonomy_terms (organization_id, kind, key, label, sort_order, is_system)
SELECT :org_id, 'INJURY_TYPE', key, label, ord, true FROM (VALUES
  ('FRACTURE','Fracture',10), ('LACERATION','Laceration or cut',20),
  ('CONTUSION','Bruise or contusion',30), ('SPRAIN','Sprain or strain',40),
  ('BURN','Burn',50), ('EYE_INJURY','Eye injury',60),
  ('CRUSH','Crush injury',70), ('CONCUSSION','Concussion',80),
  ('RESPIRATORY','Respiratory',90), ('OTHER','Other',100)
) AS t(key,label,ord);

INSERT INTO taxonomy_terms (organization_id, kind, key, label, sort_order, is_system)
SELECT :org_id, 'BODY_PART', key, label, ord, true FROM (VALUES
  ('HEAD','Head',10), ('EYE','Eye',20), ('NECK','Neck',30), ('BACK','Back',40),
  ('SHOULDER','Shoulder',50), ('ARM','Arm',60), ('HAND','Hand or finger',70),
  ('TORSO','Torso',80), ('LEG','Leg',90), ('FOOT','Foot or toe',100), ('MULTIPLE','Multiple',110)
) AS t(key,label,ord);

-- ---------------------------------------------------------------------
-- Notification rules (the defaults from 01-PRD §11.1)
-- ---------------------------------------------------------------------
INSERT INTO notification_rules (organization_id, category, channels, offsets_hours, min_severity, recipient_roles) VALUES
 (:org_id,'REPORT_SUBMITTED',       '{IN_APP,EMAIL}',          '{}',              'MODERATE', '{HSE_MANAGER,SITE_MANAGER}'),
 (:org_id,'REPORT_ACKNOWLEDGED',    '{IN_APP,EMAIL}',          '{}',              NULL,       '{}'),
 (:org_id,'INVESTIGATION_ASSIGNED', '{IN_APP,EMAIL}',          '{}',              NULL,       '{INVESTIGATOR}'),
 (:org_id,'INVESTIGATION_DUE',      '{IN_APP,EMAIL}',          '{-48,0}',         NULL,       '{INVESTIGATOR,HSE_MANAGER}'),
 (:org_id,'INVESTIGATION_SUBMITTED','{IN_APP,EMAIL}',          '{}',              NULL,       '{HSE_MANAGER}'),
 (:org_id,'INVESTIGATION_RETURNED', '{IN_APP,EMAIL}',          '{}',              NULL,       '{INVESTIGATOR}'),
 (:org_id,'ACTION_ASSIGNED',        '{IN_APP,EMAIL,WHATSAPP}', '{}',              NULL,       '{ACTION_OWNER}'),
 (:org_id,'ACTION_DUE',             '{IN_APP,EMAIL}',          '{-168,-72,-24}',  NULL,       '{ACTION_OWNER}'),
 (:org_id,'ACTION_OVERDUE',         '{IN_APP,EMAIL}',          '{24,96,168}',     NULL,       '{ACTION_OWNER}'),
 (:org_id,'ACTION_ESCALATED',       '{IN_APP,EMAIL}',          '{168,504}',       NULL,       '{SITE_MANAGER,HSE_MANAGER,EXECUTIVE}'),
 (:org_id,'ACTION_VERIFICATION',    '{IN_APP,EMAIL}',          '{}',              NULL,       '{HSE_MANAGER}'),
 (:org_id,'INCIDENT_CLOSED',        '{IN_APP}',                '{}',              NULL,       '{}'),
 (:org_id,'WEEKLY_DIGEST',          '{EMAIL}',                 '{}',              NULL,       '{HSE_MANAGER,SITE_MANAGER,EXECUTIVE}');

-- ---------------------------------------------------------------------
-- THE DEMO INCIDENT — the story you tell in the sales call
-- ---------------------------------------------------------------------
INSERT INTO incidents (
  id, organization_id, reference, report_type, status, source,
  title, description, immediate_action,
  site_id, department_id, work_area,
  category_term_id, severity, likelihood,
  occurred_at, reported_at, acknowledged_at, investigation_required,
  reported_by_user_id, acknowledged_by_user_id,
  lost_time, reportable_to_authority, estimated_cost, cost_currency)
VALUES (
  :inc_main, :org_id, app.next_reference(:org_id, 'INC'), 'INCIDENT', 'ACTIONS_PENDING', 'MOBILE_PWA',
  'Steel fixer fell 2.4 m from unguarded scaffold edge — Block C',
  'At approximately 10:15 a steel fixer working on the Block C slab edge stepped backwards onto an '
  'uncovered opening in the scaffold platform and fell approximately 2.4 m onto compacted fill. He was '
  'wearing a harness but it was not clipped to the lifeline. He was conscious throughout, complaining of '
  'pain in the right ankle and lower back. Work in the area was stopped immediately.',
  'Area barricaded, work at height stopped in Block C, injured person taken to Aga Khan Hospital by site ambulance.',
  :site_a,
  (SELECT id FROM departments WHERE organization_id = :org_id AND code = 'CIV'),
  'Block C — slab edge, level 2',
  (SELECT id FROM taxonomy_terms WHERE organization_id = :org_id AND kind='INCIDENT_CATEGORY' AND key='FALL_FROM_HEIGHT'),
  'MAJOR', 'POSSIBLE',
  now() - interval '26 days', now() - interval '26 days' + interval '38 minutes',
  now() - interval '26 days' + interval '52 minutes', true,
  :u_worker, :u_hse,
  true, true, 4200000.00, 'TZS');

INSERT INTO incident_persons (organization_id, incident_id, user_id, full_name, employer, involvement,
                              injury_type_term_id, body_part_term_id, treatment, days_lost, statement)
VALUES (:org_id, :inc_main, NULL, 'Rashid Mbwana', 'Kilimanjaro Construction Ltd', 'INJURED',
  (SELECT id FROM taxonomy_terms WHERE organization_id=:org_id AND kind='INJURY_TYPE' AND key='SPRAIN'),
  (SELECT id FROM taxonomy_terms WHERE organization_id=:org_id AND kind='BODY_PART'   AND key='FOOT'),
  'MEDICAL_TREATMENT', 9,
  'Grade 2 ankle sprain and lumbar contusion. Cleared for light duties after 9 days.');

INSERT INTO incident_persons (organization_id, incident_id, user_id, full_name, involvement, statement) VALUES
 (:org_id, :inc_main, :u_worker, NULL, 'WITNESS',
  'I was two metres away. The opening had no cover and no barrier. We had been told the covers were coming that morning.'),
 (:org_id, :inc_main, NULL, 'Emmanuel Kato', 'SUPERVISOR',
  'I did the pre-task briefing at 07:00. The scaffold was handed over the previous evening; I did not re-inspect it.');

-- Investigation
INSERT INTO investigations (id, organization_id, incident_id, status, lead_investigator_id,
                            assigned_by_user_id, assigned_at, due_at, started_at, submitted_at,
                            approved_at, approved_by_user_id, summary)
VALUES (:investigation, :org_id, :inc_main, 'APPROVED', :u_inv, :u_hse,
        now() - interval '26 days' + interval '2 hours',
        now() - interval '19 days',
        now() - interval '25 days',
        now() - interval '21 days',
        now() - interval '20 days', :u_hse,
        'A scaffold platform opening left uncovered after a night-shift material lift was not identified at '
        'handover, and the harness lifeline was not connected because no anchor point was available within reach.');

INSERT INTO investigation_timeline_entries (organization_id, investigation_id, occurred_at, description, sort_order) VALUES
 (:org_id, :investigation, now() - interval '27 days' + interval '19 hours', 'Night shift removes two platform boards to lift rebar to level 2.', 1),
 (:org_id, :investigation, now() - interval '26 days' + interval '6 hours',  'Scaffold handed over to day shift; handover checklist signed without a physical walk-through.', 2),
 (:org_id, :investigation, now() - interval '26 days' + interval '7 hours',  'Pre-task briefing held; the opening is not mentioned.', 3),
 (:org_id, :investigation, now() - interval '26 days' + interval '10 hours' + interval '15 minutes', 'Steel fixer steps back into the opening and falls 2.4 m.', 4),
 (:org_id, :investigation, now() - interval '26 days' + interval '10 hours' + interval '22 minutes', 'First aid administered; site ambulance dispatched.', 5);

INSERT INTO investigation_interviews (organization_id, investigation_id, interviewee_name, interviewed_at, notes) VALUES
 (:org_id, :investigation, 'Rashid Mbwana (injured)', now() - interval '24 days',
  'Confirms he was not clipped on. States the nearest anchor point was roughly 8 m away and the lanyard is 2 m.'),
 (:org_id, :investigation, 'Emmanuel Kato (supervisor)', now() - interval '24 days',
  'Confirms the handover checklist was signed in the site office, not on the scaffold.'),
 (:org_id, :investigation, 'Night shift charge hand', now() - interval '23 days',
  'Confirms boards were removed for the lift and states there was no instruction to reinstate or barricade them.');

INSERT INTO findings (organization_id, investigation_id, finding_type, statement, sort_order) VALUES
 (:org_id, :investigation, 'IMMEDIATE_CAUSE',  'An unguarded opening existed in the scaffold working platform.', 1),
 (:org_id, :investigation, 'IMMEDIATE_CAUSE',  'The fall-arrest harness was worn but not connected to a lifeline.', 2),
 (:org_id, :investigation, 'UNDERLYING_CAUSE', 'The scaffold handover checklist was completed without a physical inspection.', 3),
 (:org_id, :investigation, 'UNDERLYING_CAUSE', 'No continuous anchor line was installed along the Block C slab edge.', 4),
 (:org_id, :investigation, 'ROOT_CAUSE',       'The permit and handover procedure does not require a physical scaffold inspection between shifts.', 5),
 (:org_id, :investigation, 'ROOT_CAUSE',       'Work-at-height design does not specify anchor provision before platforms are released for use.', 6);

-- 5 Whys, chain 1
INSERT INTO root_causes (id, organization_id, investigation_id, problem_statement, statement, category) VALUES
 (:rc_1, :org_id, :investigation,
  'A worker fell through an uncovered opening in a scaffold platform.',
  'The shift handover procedure permits a checklist to be signed without a physical inspection of the structure.',
  'MANAGEMENT_SYSTEM');

INSERT INTO root_cause_whys (organization_id, root_cause_id, step, question, answer) VALUES
 (:org_id, :rc_1, 1, 'Why did the worker fall?',                             'He stepped backwards into an uncovered opening in the platform.'),
 (:org_id, :rc_1, 2, 'Why was the opening uncovered?',                       'Boards removed by the night shift for a material lift were not reinstated.'),
 (:org_id, :rc_1, 3, 'Why were they not reinstated?',                        'No one was assigned to restore the platform after the lift, and no barricade was required.'),
 (:org_id, :rc_1, 4, 'Why was that not caught at handover?',                 'The handover checklist was signed in the site office without walking the scaffold.'),
 (:org_id, :rc_1, 5, 'Why was signing without inspection acceptable?',       'The procedure does not require a physical inspection or a countersignature on the structure.');

-- 5 Whys, chain 2
INSERT INTO root_causes (id, organization_id, investigation_id, problem_statement, statement, category) VALUES
 (:rc_2, :org_id, :investigation,
  'The fall-arrest harness was worn but not connected.',
  'Work-at-height planning does not require anchor provision to be verified before a platform is released for use.',
  'PROCESS');

INSERT INTO root_cause_whys (organization_id, root_cause_id, step, question, answer) VALUES
 (:org_id, :rc_2, 1, 'Why was the harness not connected?',                 'There was no reachable anchor point at the work position.'),
 (:org_id, :rc_2, 2, 'Why was there no reachable anchor?',                 'No continuous horizontal lifeline had been installed on the Block C edge.'),
 (:org_id, :rc_2, 3, 'Why had none been installed?',                       'The lifeline was scheduled after slab edge works, not before.'),
 (:org_id, :rc_2, 4, 'Why was it sequenced that way?',                     'The work-at-height plan treats anchor installation as a follow-on activity.'),
 (:org_id, :rc_2, 5, 'Why does the plan allow that sequence?',             'Anchor provision is not a gate condition for releasing a platform for use.');

-- ---------------------------------------------------------------------
-- CAPA — one verified closed, one in progress, one overdue, one preventive
-- ---------------------------------------------------------------------
INSERT INTO actions (organization_id, reference, title, description, action_type, status, priority,
                     hierarchy_level, incident_id, investigation_id, root_cause_id, site_id,
                     owner_user_id, verifier_user_id, created_by_user_id,
                     original_due_date, due_date, started_at, submitted_at, verified_at, closed_at,
                     effectiveness, verification_comments)
VALUES
 (:org_id, app.next_reference(:org_id,'ACT'),
  'Install continuous horizontal lifeline along Block C slab edge',
  'Install a certified horizontal lifeline system covering the full Block C level 2 slab edge before any '
  'further edge work is released.', 'CORRECTIVE', 'VERIFIED_CLOSED', 'URGENT', 'ENGINEERING',
  :inc_main, :investigation, :rc_2, :site_a, :u_owner, :u_hse, :u_hse,
  (now() - interval '12 days')::date, (now() - interval '12 days')::date,
  now() - interval '19 days', now() - interval '14 days', now() - interval '13 days', now() - interval '13 days',
  'EFFECTIVE', 'Lifeline installed and load-tested. Verified on site with the scaffold contractor. Certificate on file.');

INSERT INTO actions (organization_id, reference, title, description, action_type, status, priority,
                     hierarchy_level, incident_id, investigation_id, root_cause_id, site_id,
                     owner_user_id, verifier_user_id, created_by_user_id,
                     original_due_date, due_date, started_at)
VALUES
 (:org_id, app.next_reference(:org_id,'ACT'),
  'Revise scaffold handover procedure to require a physical joint inspection',
  'Update SP-014 so that no scaffold platform may be handed between shifts without a joint physical '
  'inspection and countersignature by both charge hands, recorded on the structure.',
  'PREVENTIVE', 'IN_PROGRESS', 'HIGH', 'ADMINISTRATIVE',
  :inc_main, :investigation, :rc_1, :site_a, :u_site, :u_hse, :u_hse,
  (now() + interval '9 days')::date, (now() + interval '9 days')::date, now() - interval '15 days');

INSERT INTO actions (organization_id, reference, title, description, action_type, status, priority,
                     hierarchy_level, incident_id, investigation_id, root_cause_id, site_id,
                     owner_user_id, verifier_user_id, created_by_user_id,
                     original_due_date, due_date)
VALUES
 (:org_id, app.next_reference(:org_id,'ACT'),
  'Toolbox talk on platform openings and tie-off discipline for all Block C crews',
  'Deliver and record a toolbox talk covering platform integrity, opening covers and 100% tie-off, to every '
  'crew working at height on Block C.', 'CORRECTIVE', 'OPEN', 'HIGH', 'ADMINISTRATIVE',
  :inc_main, :investigation, :rc_1, :site_a, :u_owner, :u_hse, :u_hse,
  (now() - interval '6 days')::date, (now() - interval '6 days')::date);   -- deliberately overdue

INSERT INTO actions (organization_id, reference, title, description, action_type, status, priority,
                     hierarchy_level, incident_id, investigation_id, root_cause_id, site_id,
                     owner_user_id, verifier_user_id, created_by_user_id,
                     original_due_date, due_date)
VALUES
 (:org_id, app.next_reference(:org_id,'ACT'),
  'Make anchor provision a gate condition in the work-at-height plan',
  'Amend the work-at-height planning standard so a platform cannot be released for use until anchor points '
  'or a lifeline are installed and certified.', 'PREVENTIVE', 'OPEN', 'HIGH', 'ELIMINATION',
  :inc_main, :investigation, :rc_2, NULL, :u_hse, :u_admin, :u_hse,
  (now() + interval '21 days')::date, (now() + interval '21 days')::date);

INSERT INTO action_updates (organization_id, action_id, user_id, note, progress_percent, status_from, status_to)
SELECT :org_id, a.id, :u_owner,
       'Scaffold contractor mobilised. Lifeline anchors drilled and epoxied; load test scheduled.', 60, 'OPEN', 'IN_PROGRESS'
FROM actions a WHERE a.organization_id = :org_id AND a.title LIKE 'Install continuous horizontal lifeline%';

INSERT INTO comments (organization_id, entity, entity_id, user_id, body) VALUES
 (:org_id, 'INCIDENT', :inc_main, :u_hse,
  'Notified the labour officer within 24 hours as a reportable lost-time injury. Reference OSH/DSM/2026/0117.'),
 (:org_id, 'INCIDENT', :inc_main, :u_exec,
  'Reviewed at the Monday operations meeting. All Block C edge work stays stopped until the lifeline is certified.');

-- ---------------------------------------------------------------------
-- Background volume — 12 months of events so every dashboard tile has data
-- ---------------------------------------------------------------------
INSERT INTO incidents (organization_id, reference, report_type, status, source, description,
                       site_id, category_term_id, severity, likelihood,
                       occurred_at, reported_at, acknowledged_at, closed_at, closure_statement,
                       reported_by_user_id, acknowledged_by_user_id, closed_by_user_id, lost_time)
SELECT
  :org_id,
  app.next_reference(:org_id,'INC'),
  (ARRAY['NEAR_MISS','HAZARD','OBSERVATION','HAZARD','NEAR_MISS','INCIDENT']::report_type[])[1 + (g % 6)],
  (ARRAY['CLOSED','CLOSED','CLOSED','ACTIONS_PENDING','SUBMITTED']::report_status[])[1 + (g % 5)],
  (ARRAY['WEB','MOBILE_PWA','MOBILE_PWA','ANONYMOUS_LINK','WHATSAPP']::source_channel[])[1 + (g % 5)],
  (ARRAY[
    'Excavation edge left unbarricaded overnight near the haul road crossing.',
    'Reversing tipper without a banksman in the batching plant yard.',
    'Frayed sling observed on the tower crane hook block during pre-use check.',
    'Housekeeping: offcuts and banding accumulating on the level 3 access route.',
    'Worker observed grinding without a face shield at the rebar yard.',
    'Diesel spill of about 20 litres from a bowser coupling near the wash bay.',
    'Temporary lighting cable run through standing water in the basement.',
    'Load lifted over an occupied walkway; area cleared before the next lift.'
  ])[1 + (g % 8)],
  (CASE WHEN g % 3 = 0 THEN :site_b ELSE :site_a END)::uuid,
  (SELECT id FROM taxonomy_terms WHERE organization_id=:org_id AND kind='INCIDENT_CATEGORY'
    ORDER BY sort_order OFFSET (g % 12) LIMIT 1),
  (ARRAY['NEGLIGIBLE','MINOR','MINOR','MODERATE','MINOR','MODERATE','MAJOR']::severity_level[])[1 + (g % 7)],
  (ARRAY['RARE','UNLIKELY','POSSIBLE','LIKELY','POSSIBLE']::likelihood_level[])[1 + (g % 5)],
  now() - ((g * 2.7)::int || ' days')::interval,
  now() - ((g * 2.7)::int || ' days')::interval + ((3 + g % 40) || ' hours')::interval,
  now() - ((g * 2.7)::int || ' days')::interval + ((5 + g % 40) || ' hours')::interval,
  CASE WHEN g % 5 < 3 THEN now() - ((g * 2.7)::int || ' days')::interval + ((6 + g % 20) || ' days')::interval END,
  CASE WHEN g % 5 < 3 THEN 'Controls implemented and verified; no further action required.' END,
  (ARRAY[:u_worker, :u_owner, :u_site, :u_inv]::uuid[])[1 + (g % 4)],
  :u_hse,
  (CASE WHEN g % 5 < 3 THEN :u_hse END)::uuid,
  (g % 23 = 0)
FROM generate_series(1, 130) AS g;

-- A spread of standalone actions so the CAPA dashboard is populated
INSERT INTO actions (organization_id, reference, title, action_type, status, priority, hierarchy_level,
                     site_id, owner_user_id, verifier_user_id, created_by_user_id,
                     original_due_date, due_date, verified_at, effectiveness)
SELECT
  :org_id,
  app.next_reference(:org_id,'ACT'),
  (ARRAY[
    'Barricade and light the excavation edge on the haul road crossing',
    'Reinstate banksman control for all reversing plant in the yard',
    'Quarantine and replace the defective lifting sling',
    'Clear and re-mark the level 3 access route',
    'Re-issue face shields and re-brief the rebar yard crew',
    'Repair the bowser coupling and place a drip tray',
    'Reroute temporary lighting clear of standing water',
    'Enforce exclusion zones under all crane lifts'
  ])[1 + (g % 8)],
  (ARRAY['CORRECTIVE','CORRECTIVE','PREVENTIVE']::action_type[])[1 + (g % 3)],
  (ARRAY['VERIFIED_CLOSED','VERIFIED_CLOSED','VERIFIED_CLOSED','IN_PROGRESS','OPEN','PENDING_VERIFICATION']::action_status[])[1 + (g % 6)],
  (ARRAY['LOW','MEDIUM','HIGH','URGENT']::priority_level[])[1 + (g % 4)],
  (ARRAY['ENGINEERING','ADMINISTRATIVE','PPE','SUBSTITUTION','ADMINISTRATIVE']::hierarchy_of_control[])[1 + (g % 5)],
  (CASE WHEN g % 3 = 0 THEN :site_b ELSE :site_a END)::uuid,
  (ARRAY[:u_owner, :u_site, :u_inv]::uuid[])[1 + (g % 3)],
  :u_hse, :u_hse,
  (now() - ((g * 2.3)::int || ' days')::interval + interval '14 days')::date,
  (now() - ((g * 2.3)::int || ' days')::interval + ((14 + (g % 3) * 7) || ' days')::interval)::date,
  -- deliberately mixed: roughly a quarter of closures land after the due date so the
  -- demo dashboard shows a realistic on-time rate rather than a suspicious 100%
  CASE WHEN g % 6 < 3 THEN now() - ((g * 2.3)::int || ' days')::interval
                           + ((13 + (g % 4) * 6) || ' days')::interval END,
  CASE WHEN g % 6 < 3 THEN (ARRAY['EFFECTIVE','EFFECTIVE','PARTIALLY_EFFECTIVE']::effectiveness_rating[])[1 + (g % 3)] END
FROM generate_series(1, 90) AS g;

-- Audit trail for the demo incident so the History tab is not empty
INSERT INTO audit_events (organization_id, actor_user_id, actor_label, action, entity, entity_id,
                          entity_reference, changes, created_at)
SELECT :org_id, a.actor::uuid, a.label, a.act::audit_action, 'INCIDENT', :inc_main,
       (SELECT reference FROM incidents WHERE id = :inc_main), a.changes::jsonb, a.at
FROM (VALUES
 (:u_worker, 'Amina Hassan',      'CREATE',        '{"status":{"from":null,"to":"SUBMITTED"}}',                     now() - interval '26 days' + interval '38 minutes'),
 (:u_hse,    'Grace Kimaro',      'STATUS_CHANGE', '{"status":{"from":"SUBMITTED","to":"ACKNOWLEDGED"}}',           now() - interval '26 days' + interval '52 minutes'),
 (:u_hse,    'Grace Kimaro',      'UPDATE',        '{"severity":{"from":null,"to":"MAJOR"},"likelihood":{"from":null,"to":"POSSIBLE"}}', now() - interval '26 days' + interval '55 minutes'),
 (:u_hse,    'Grace Kimaro',      'ASSIGN',        '{"lead_investigator":{"from":null,"to":"Peter Massawe"}}',      now() - interval '26 days' + interval '2 hours'),
 (:u_inv,    'Peter Massawe',     'STATUS_CHANGE', '{"investigation_status":{"from":"IN_PROGRESS","to":"SUBMITTED"}}', now() - interval '21 days'),
 (:u_hse,    'Grace Kimaro',      'APPROVE',       '{"investigation_status":{"from":"SUBMITTED","to":"APPROVED"}}', now() - interval '20 days'),
 (:u_hse,    'Grace Kimaro',      'EXPORT',        '{"format":"PDF","scope":"incident"}',                           now() - interval '19 days')
) AS a(actor, label, act, changes, at);

REFRESH MATERIALIZED VIEW mv_incident_daily;
REFRESH MATERIALIZED VIEW mv_action_daily;

COMMIT;

-- Sanity output
SELECT 'organizations' AS entity, count(*) FROM organizations
UNION ALL SELECT 'users',          count(*) FROM users
UNION ALL SELECT 'sites',          count(*) FROM sites
UNION ALL SELECT 'incidents',      count(*) FROM incidents
UNION ALL SELECT 'investigations', count(*) FROM investigations
UNION ALL SELECT 'root_causes',    count(*) FROM root_causes
UNION ALL SELECT 'actions',        count(*) FROM actions
UNION ALL SELECT 'overdue actions', count(*) FROM actions
  WHERE status IN ('OPEN','IN_PROGRESS','REJECTED') AND due_date < current_date
UNION ALL SELECT 'audit_events',   count(*) FROM audit_events
ORDER BY 1;
